#! /usr/bin/python2.7

GROM_BASE=3
MODULE="phm3109"

with file(MODULE+"c.bin", 'r+b') as fh:
    fh.seek(0x0deb)
    fh.write( chr(GROM_BASE * 4))
fh.close

with file(MODULE+"g.bin", 'r+b') as fh:
    fh.seek(0)
    fh.write( chr(0xa5))
    fh.write( chr(0x5a))
    fh.seek(3)
    fh.write( chr(GROM_BASE-2) )

    fh.seek(0x2aab)
    fh.write( chr(GROM_BASE * 4))
    fh.seek(0x2ab7)
    fh.write( chr(GROM_BASE * 4))

    fh.seek(0x2b5d)
    fh.write( chr((GROM_BASE * 4) + 2))
    fh.seek(0x2b65)
    fh.write( chr((GROM_BASE * 4) + 2))
    fh.seek(0x2b6d)
    fh.write( chr(GROM_BASE * 4))
    fh.seek(0x2b73)
    fh.write( chr(GROM_BASE * 4))

    fh.seek(0x474b)
    fh.write( chr(GROM_BASE * 4))

fh.close
