#! /usr/bin/python2.7

import mmap

# Multiplan GROM itself does not need patch, but disk does.

GROM_BASE=4
MODULE="phm3113"

with file(MODULE+"g.bin", 'r+b') as fh:
    fh.seek(0)
    fh.write( chr(0xa5))
    fh.write( chr(0x5a))
fh.close

# handle different versions of the disk

with open(MODULE+".dsk", "rb+") as fh:
    mm = mmap.mmap(fh.fileno(), 0)
    i = mm.find('\x98\x00')
    while i > 1:
	print hex(i)
	mm.seek(i+1)
	mm.write(chr(GROM_BASE * 4))
	mm.flush()
	i = mm.find('\x98\x00')
    mm.close()
fh.close()
